{% set version = "0.1.1" %}

package:
  name: pybvrf
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pybvrf/pybvrf-{{ version }}.tar.gz
  sha256: 916dd473cd67c7536b490e03e4d32c454502e9c923a144fbe9e34f6e5821f79b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.9.22,<0.10.0
    - pip
  run:
    - python >={{ python_min }}
    - jsonschema >=4.26.0
    - mne-base >=1.11.0
    - numpy >=2.2.0

test:
  imports:
    - pybvrf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pybvrf/
  summary: A Python package for working with BrainVision Recording Format (BVRF) files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
