{% set version = "0.1.2" %}

package:
  name: pybvrf
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pybvrf/pybvrf-{{ version }}.tar.gz
  sha256: e1978553413b737e1e2f7ac6d4ac73d39ad7d2ba1d8634d00a9f75744eca4c67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.9.22,<0.10.0
    - pip
  run:
    - python >={{ python_min }}
    - jsonschema >=4.26.0
    - mne-base >=1.11.0
    - numpy >=2.2.0

test:
  imports:
    - pybvrf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pybvrf/
  summary: A Python package for working with BrainVision Recording Format (BVRF) files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
