{% set version = "0.1.4" %}
{% set python_min = "3.12" %}

package:
  name: pybvrf
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pybvrf/pybvrf-{{ version }}.tar.gz
  sha256: dab55e55bcd0e6fd816f5963a6fb87affc46f9ab80de839e9198e6e8c0ddbd03

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.9.22,<0.10.0
    - pip
  run:
    - python >={{ python_min }}
    - jsonschema >=4.26.0
    - mne-base >=1.11.0
    - numpy >=2.2.0

test:
  imports:
    - pybvrf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pybvrf/
  summary: A Python package for working with BrainVision Recording Format (BVRF) files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
